# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: uholee.log
email: developer.uho@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This page is for logging my Q/As during works so that I can remind myself and reuse them later.
  Feel free to comment on my posts with any opinions..
# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://uholee.github.io" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title/
# twitter_username: jekyllrb
github_username:  uholee

# Build settings
markdown: kramdown
